# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccd8a30354923ef607c99d64c78ed34513026a51735698cf6e2911cf4cbe0c1764a7c32e036396a9ce34e209f5a402251aaa781d863b0a0bebef9fb4e1142d7a

test:
  secret_key_base: 512e03691a76b87e07fdfaf521598f6adf0db8cbb7ae2783e0b62168d780375bc4120dd6aec2240a8460c5d10b2e43a7b72312d43c0fdccb4e345e93324e887d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
